const menuData = {
  restaurant: {
    id: "33723",
    name: "KFC",
    city: "Pune",
    rating: 4.4,
    cuisines: ["Burgers", "Fast Food", "Chicken", "Snacks"],
    costForTwo: 400,
    deliveryTime: 30,
    address: "Shop No. 12, FC Road, Shivajinagar, Pune - 411005",
  },
  categories: [
    {
      title: "Recommended",
      items: [
        {
          id: "item1",
          name: "Chicken Zinger Burger",
          price: 249,
          description: "Crispy chicken fillet with spicy zinger sauce, lettuce & mayo in a toasted bun",
          imageId: "dummy-image-1",
          isVeg: false,
          rating: 4.5,
        },
        {
          id: "item2",
          name: "Chicken Bucket (8 Pcs)",
          price: 699,
          description: "8 pieces of KFC's signature crispy fried chicken served in a classic bucket",
          imageId: "dummy-image-2",
          isVeg: false,
          rating: 4.7,
        },
        {
          id: "item3",
          name: "Popcorn Chicken",
          price: 179,
          description: "Bite-sized crispy chicken popcorn tossed in secret seasoning",
          imageId: "dummy-image-3",
          isVeg: false,
          rating: 4.3,
        },
      ],
    },
    {
      title: "Burgers",
      items: [
        {
          id: "item4",
          name: "Classic Chicken Burger",
          price: 199,
          description: "Classic crispy chicken patty with fresh veggies and creamy mayo",
          imageId: "dummy-image-4",
          isVeg: false,
          rating: 4.2,
        },
        {
          id: "item5",
          name: "Double Crunch Burger",
          price: 329,
          description: "Double layered crispy chicken with extra crunch coating and cheese",
          imageId: "dummy-image-5",
          isVeg: false,
          rating: 4.6,
        },
        {
          id: "item6",
          name: "Veg Burger",
          price: 149,
          description: "Crispy veg patty with fresh lettuce, tomato and special sauce",
          imageId: "dummy-image-6",
          isVeg: true,
          rating: 3.9,
        },
      ],
    },
    {
      title: "Chicken",
      items: [
        {
          id: "item7",
          name: "Hot Wings (6 Pcs)",
          price: 299,
          description: "Spicy hot chicken wings glazed with smoky sauce",
          imageId: "dummy-image-7",
          isVeg: false,
          rating: 4.4,
        },
        {
          id: "item8",
          name: "Grilled Chicken Strips",
          price: 259,
          description: "Tender grilled chicken strips served with dipping sauce",
          imageId: "dummy-image-8",
          isVeg: false,
          rating: 4.1,
        },
        {
          id: "item9",
          name: "Chicken Drumsticks (2 Pcs)",
          price: 189,
          description: "Juicy crispy fried chicken drumsticks with original recipe coating",
          imageId: "dummy-image-9",
          isVeg: false,
          rating: 4.3,
        },
      ],
    },
    {
      title: "Snacks & Sides",
      items: [
        {
          id: "item10",
          name: "Coleslaw",
          price: 69,
          description: "Creamy homestyle coleslaw made fresh daily",
          imageId: "dummy-image-10",
          isVeg: true,
          rating: 4.0,
        },
        {
          id: "item11",
          name: "Crispy Fries (Large)",
          price: 119,
          description: "Golden crispy fries seasoned with special KFC spice blend",
          imageId: "dummy-image-11",
          isVeg: true,
          rating: 4.2,
        },
        {
          id: "item12",
          name: "Corn on the Cob",
          price: 99,
          description: "Buttered corn on the cob — sweet, tender and delicious",
          imageId: "dummy-image-12",
          isVeg: true,
          rating: 4.1,
        },
      ],
    },
    {
      title: "Beverages",
      items: [
        {
          id: "item13",
          name: "Pepsi (Large)",
          price: 99,
          description: "Chilled Pepsi soft drink — large serving",
          imageId: "dummy-image-13",
          isVeg: true,
          rating: 4.0,
        },
        {
          id: "item14",
          name: "Mountain Dew",
          price: 79,
          description: "Refreshing citrus-flavoured soft drink",
          imageId: "dummy-image-14",
          isVeg: true,
          rating: 4.0,
        },
        {
          id: "item15",
          name: "Chocolate Shake",
          price: 149,
          description: "Rich and creamy chocolate milkshake",
          imageId: "dummy-image-15",
          isVeg: true,
          rating: 4.5,
        },
      ],
    },
    {
      title: "Desserts",
      items: [
        {
          id: "item16",
          name: "Choco Lava Cake",
          price: 129,
          description: "Warm chocolate cake with a gooey molten chocolate centre",
          imageId: "dummy-image-16",
          isVeg: true,
          rating: 4.6,
        },
        {
          id: "item17",
          name: "Soft Serve Ice Cream",
          price: 59,
          description: "Classic vanilla soft serve in a cone",
          imageId: "dummy-image-17",
          isVeg: true,
          rating: 4.3,
        },
      ],
    },
  ],
};

module.exports = menuData;
